



services:
  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    user: "1000:1000"           # change if your UID:GID is different
    ports:
      - "4533:4533"             # access locally at http://localhost:4533
    restart: unless-stopped
    environment:
      - ND_LOGLEVEL=info        # optional: debug/info/warn
      - ND_SESSIONTIMEOUT=24h
      - ND_BIND=0.0.0.0         # listen on all interfaces
    volumes:
      - ./data:/data            # Navidrome DB, cache, config
      - ./music:/music:ro       # your music collection (read-only inside container)
    networks:
      - web

    
  #nginx reverse proxy set up
  nginx:
    image:  nginx:latest
    container_name: nginx
    ports:
      -  "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - navidrome
    networks:
      - web
    # end of reverse proxy set up
  
  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok
    depends_on:
      - nginx
    restart: unless-stopped
    command: http nginx:80
    environment:
      NGROK_AUTHTOKEN: ${NGROK_TOKEN}   # replace with your free ngrok token
    networks:
      -  web


# newtwork set up
networks:
  web:
    driver: bridge
